### ISSUE TITLE
Source is unavailable

### ISSUE THREAD

**Issue by revunix** [micahmo/twitch2tuner#13]
Hello,

I have set up the server correctly. The respective streamers are also displayed to me, but the stream is not loaded. Is this a known problem? 

**Edit:** Okay, it's because I have transcoding disabled. Is there a way to view the feed without transcoding?

![CleanShot 2023-10-23 at 00 44 55](https://github.com/micahmo/twitch2tuner/assets/4172418/a3a65c16-b836-4629-ba04-b66397126155)
![CleanShot 2023-10-23 at 00 45 21](https://github.com/micahmo/twitch2tuner/assets/4172418/a5f80976-460c-4a9f-9d19-346dea9781aa)

**Comment by micahmo** [comment]
Hey @revunix, glad you figured out the issue! I would guess that this depends on the codec of the stream and the capabilities of the client you're using. For example, even with transcoding enabled, I could never get this to work using Plex in the browser. As a result, unfortunately, I think you'll be pretty limited here. By disabling transcoding, you're essentially saying that your client must have the ability to play the stream exactly as it comes from Twitch, which may not be possible. 😞
