### ISSUE TITLE
Twitch Turbo/Subscriber Integrarion 

### ISSUE THREAD

**Issue by yoshi43** [micahmo/twitch2tuner#16]
Is there any way to pass through the --twitch-api-header=Authorization=OAuth argument to streamlink to skip commercials if you are a subscriber or twitch turbo member?

**Comment by micahmo** [comment]
Hey @yoshi43, thanks for the question! Right now, no. You can see the call to `streamlink` below and it doesn't have that argument.

https://github.com/micahmo/twitch2tuner/blob/1a57c822cf9d307c7d50b5aaaf0e40565a59177e/twitch2tuner/StreamUtility.cs#L81

It probably wouldn't be too hard to add, but as I'm not a subscriber/member it would be hard for me to test. However, I'd be open to contributions!

**Comment by yoshi43** [comment]
Thank you so much!

I tried editing line 81 in that file, but was still getting commercials.

Adding `\"--http-header=Authorization=OAuth myoauthcode\"` in between `best` and `--quiet `to line 71 of that same file worked perfectly.

https://github.com/micahmo/twitch2tuner/blob/1a57c822cf9d307c7d50b5aaaf0e40565a59177e/twitch2tuner/StreamUtility.cs#L71

**Comment by micahmo** [comment]
I'm so glad to hear that worked! Would you feel comfortable opening a PR for this change? You can either add a new environment variable to capture the OAuth token, or you might be able to use the mechanism that we already have for capturing the user's access token by having them log in.

https://github.com/micahmo/twitch2tuner/blob/1a57c822cf9d307c7d50b5aaaf0e40565a59177e/twitch2tuner/TwitchApiManager.cs#L137-L138

https://github.com/micahmo/twitch2tuner?tab=readme-ov-file#followed-channels

**Comment by yoshi43** [comment]
I really wish I could. Unfortunately I think that’s just too far past my ability level. 

The struggle was real just trying to figure out how to build and pull a docker image from my local files instead of the link.

What I can do is buy you some coffees for how quickly you have provided help and for the application in general. If you wanted to subscribe to turbo with that, I wouldn’t fight you, but feel no obligation.

**Comment by micahmo** [comment]
That's very generous of you, thank you!

If you can help to answer a couple questions, I'll see if I can make the code change.
1. Are you using the login flow described in the README to authenticate twitch2tuner with Twitch so it can retrieve your followed channels? Or are you setting the `CHANNELS_FOLLOWED` environment variable?
2. If the former, can you tell if the `AccessToken` returned by that login flow is the same (or at least the same format) as the OAuth token that you're passing to the HTTP header?

If you're not sure, no problem. Thanks!

**Comment by yoshi43** [comment]
1) I am setting the `CHANNELS_FOLLOWED` environmental variable.

2) I can try to setup the former and see if it is the same or same format if that helps

**Comment by micahmo** [comment]
Thanks for the response! For now, don't worry about doing anything. I want to see if I can get it to work using that flow. I can always add a separate environment variable, but I first need to understand the relationship between the OAuth token that `streamlink` wants to use, and the one that `twitch2tuner` obtains. I will get back to you!

**Comment by micahmo** [comment]
Hey @yoshi43, I just wanted to provide a quick update. Based on the Streamlink documentation, it looks like the OAuth token must be obtained from a browser during an authenticated session on twitch.tv. It looks like there's no way to programmatically obtain the token, like `twitch2tuner` is doing for the API to retrieve followed channels. Therefore, the best path forward would be to add a new environment variable where the user can manually specify their token.

BTW, while reading Streamlink documentation, I also found the `--twitch-disable-ads` argument. It didn't seem to get rid of the ad placeholders for me, but I figured it wouldn't hurt to keep in there.

I published all of these changes, including updates to the README regarding [how to use the new env var](https://github.com/micahmo/twitch2tuner?tab=readme-ov-file#other-options). If you pull the `latest` Docker image tag you should be able to test the changes.

Please let me know how it goes!

**Comment by yoshi43** [comment]
Pulled the latest image and set the environment variable and all seems to be working

**Comment by micahmo** [comment]
I'm so glad to hear that! Best of luck with everything and thanks for checking out this project. 😊
