### ISSUE TITLE
Issue Pulling Guide

### ISSUE THREAD

**Issue by Avery579** [micahmo/twitch2tuner#18]
In Plex, I get the error "There was a problem fetching channel mappings. Please try again later." when trying to add the guide.  It seems to fail before the sent message in the log appears. Any suggestions on this?

**Comment by micahmo** [comment]
Hi @Avery579, at what step of the process did you get this message? Can you send a screenshot?

**Comment by Avery579** [comment]
Sure. I get the error when setting up the tuner in Plex. Attached is a screenshot. I blurred out the last part of the IP.
![chrome_fYrhdOSnlc](https://github.com/user-attachments/assets/2e391f34-88d9-480b-a7fa-9ed463bd9442)

**Comment by micahmo** [comment]
Can you navigate to this address in a browser?

![image](https://github.com/user-attachments/assets/05358e89-18e6-4edb-90c2-8f1357d69b02)

And if so, what does it look like?

**Comment by Avery579** [comment]
Yeah and it looks like a xml document. I was able to fix this by unfollowing quite a a few people. I had a little over 609 people followed and over half I didn't even watch anymore. I got it cut down to around 300 and it pulled the guide. I think the issue was Plex was timing out before the xml doc could be pulled by Plex

**Comment by micahmo** [comment]
Ahh, nice find. Yeah I bet that's exactly what it was. Are things working now? Are we good to close this issue? Thanks!

**Comment by Avery579** [comment]
Yeah we are good to close. Thanks for the help!
