### ISSUE TITLE
Change Show Icon to Channel Logo if Stream is "Just Chatting"

### ISSUE THREAD

**Issue by databoy2k** [micahmo/twitch2tuner#5]
When twitch2tuner builds its epg, it assigns the shows the icon of whichever game is the "category" of the stream. That's fine for streams that use typical box art, but the most common stream type is "Just Chatting" which features an icon of a woman with a coffee cup in front of a microphone.

That's totally irrelevant for those streams.

Is there a way to detect if the category is "Just Chatting" and then use the channel's logo instead?

**Comment by micahmo** [comment]
Hey @databoy2k, great suggestion. I've added conditional support for this feature based on an environment variable. Grab the latest Docker image, set `USE_PROFILE_AS_JUST_CHATTING` to `true`, and it should do what you want. Let me know what you think!

**Comment by databoy2k** [comment]
Absolutely awesome! It works like a charm. Quick refresh of guide data and I no longer have a coffee cup on my Just Chatting channels. 

Thanks a ton!
