### ISSUE TITLE
Can't Pull Docker Image

### ISSUE THREAD

**Issue by DrDmoney365** [micahmo/twitch2tuner#7]
Can't pull the image

root@docker:/srv/twitch2tuner# docker pull twitch2tuner
Using default tag: latest
Error response from daemon: pull access denied for twitch2tuner, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by micahmo** [comment]
Hi @DrDmoney365, sorry about that. The container is now hosted on the GitHub Container Registry, not Docker Hub. Try this command.

``` bash
docker pull ghcr.io/micahmo/twitch2tuner
```

I've updated the README to reflect this.

**Comment by DrDmoney365** [comment]
Thank you. That did it!
