### ISSUE TITLE
XMLTV Guide Not Working

### ISSUE THREAD

**Issue by DrDmoney365** [micahmo/twitch2tuner#8]
I've followed the below steps:

Before allowing you to continue, Plex wants to discover the guide. There is a prompt to enter a ZIP code, but the Twitch guide is served by twitch2tuner, so click "Have an XMLTV guide on your server? Click here to use that instead." Then enter the address of the server, followed by /epg.xml, like http://192.168.1.234:22708/epg.xml. You may enter anything for the Guide Title. Click Continue.

I've made sure that http://192.168.1.234:22708/epg.xml is the correct path to my xml file as that IP/Port is the full path to that file. It does appear that it has proper information in it, but Plex doesn't seem to want to update the information on the TV+DVR page. I've attached a screen shot of what Plex shows. I've tried refreshing the guide, but it still doesn't seem to want to pick up the information from the XML file.
![Plex](https://user-images.githubusercontent.com/125497364/219135720-88688d01-db1c-42fe-9492-c158ebab0117.png)

**The epg.xml file is below:**
https://pastebin.com/0Fv7sS7u

**Relevent Plex Log Files are below:**
https://pastebin.com/81cTQRns

**Comment by DrDmoney365** [comment]
Maybe I am just impatient because an hour later it's working. I'll leave this issue open if you'd like to take a look or comment but seems to be working now. Thanks for your work on this. Really appreciated to get my Twitch Streams into Plex.

**Comment by micahmo** [comment]
Thanks for the update! I have had issues with Plex reading the EPG, but they are usually evident in the logs. I didn't see anything interesting in your logs, so I was hoping it was just a matter of time until it fully loaded. 😊

If everything runs smoothly for a while, feel free to close this. Thanks!

P.S. Remember that Plex will only update the guide at most once per hour, meaning that a live streamer may not appear. But if you know they're live, you can still play the stream.
